LANGUAGES = {
    'uz': {
        'welcome': "Assalomu alaykum {mention}! \n\nBo'stonliq tuman ixtisoslashtirilgan maktabining murojaatlar uchun botiga xush kelibsiz.\n\n📨 Anonim murojaat: /anonim\nℹ️ Maktab haqida: /info\n🔗 Telegram kanal va Discord server: /links",
        'info_text': "🏫 Bizning maktabimiz 2022-yilda tashkil etilgan bo'lib, asosiy maqsad o'quvchilarga sifatli ta'lim va keng imkoniyatlar yaratishdir. Maktabimiz zamonaviy o'quv muassasasi bo'lib 5–11-sinflar uchun yuqori sifatli ta'lim beradi. Maktab jamoasi do'stona hamkorlikka tayyor.\n\nMaktabimizda:\n- Zamonaviy fanlar darslari (matematika, fizika, ingliz tili, kimyo, biologiya va boshqalar)\n- Sport va ijodiy to'garaklar.\n- Tanlov va loyihalarda qatnashish imkoniyati mavjud.\n\nSiz biz bilan bilim va do'stlikni rivojlantirasiz.\nKo'proq yangiliklar uchun Telegram kanalimizga qo'shiling!",
        'links_text': "📢 Telegram kanal:\nhttps://t.me/Bustanlikspecializedschool\n\n🎮 Discord server (run and managed by senior student):\nhttps://discord.gg/RsSFaC8zX",
        'anonim_start_msg': "✍️ Murojaatingizni yozishingiz mumkin.\n\n📎 Matn, rasm, ovozli xabar yoki fayl yuborishingiz mumkin.",
        'anonim_category_prompt': "Murojaatingiz turini tanlang:",
        'category_suggestion': "Taklif",
        'category_complaint': "Shikoyat",
        'category_question': "Savol",
        'new_anonim_request': "📩 Yangi anonim murojaat",
        'admin_reply_button': "Javob berish",
        'user_id_not_found': "❌ Foydalanuvchi ID topilmadi. Iltimos, 'Javob berish' tugmasi orqali javob bering.",
        'admin_reply_prompt': "Foydalanuvchi ID: `{user_id}` ga javob yozishingiz mumkin.",
        'admin_reply_sent': "✅ Javob yuborildi.",
        'error_occurred': "❌ Xatolik yuz berdi. Qayta urinib ko'ring.",
        'content_not_accepted': "⚠️ Bu turdagi kontent qabul qilinmaydi.",
        'request_sent': "✅ Murojaatingiz yuborildi. Rahmat.",
        'language_select_prompt': "Tilni tanlang: / Choose language: / Выберите язык:",
        'language_selected': "Til O'zbek tiliga o'rnatildi.",
        'admin_answer': "📬 Admin javobi",
        'status_title': "Xabar holati",
        'status_category': "Kategoriya",
        'status_label': "Holat",
        'status_sent_at': "Yuborilgan vaqt",
        'status_answered_at': "Javob vaqti",
        'status_no_messages': "Siz hali xabar yubormagansiz.",
        'status_pending': "Kutilmoqda",
        'status_answered': "Javob berildi",
        'status_reviewing': "Ko'rib chiqilmoqda",
    },
    'ru': {
        'welcome': "Привет {mention}! \n\nДобро пожаловать в бот для обращений Специализированной школы Бустaнликского района.\n\n📨 Анонимное обращение: /anonim\nℹ️ О школе: /info\n🔗 Telegram канал и Discord сервер: /links",
        'info_text': "🏫 Наша школа была основана в 2022 году, и основная цель - предоставить учащимся качественное образование и широкие возможности. Наша школа - это современное учебное заведение, предоставляющее высококачественное образование для 5-11 классов. Коллектив школы готов к дружескому сотрудничеству.\n\nВ нашей школе:\n- Современные уроки по предметам (математика, физика, английский язык, химия, биология и другие)\n- Спортивные и творческие кружки.\n- Возможность участвовать в конкурсах и проектах.\n\nВы будете развивать знания и дружбу с нами.\nПрисоединяйтесь к нашему Telegram-каналу для получения дополнительных новостей!",
        'links_text': "📢 Telegram канал:\nhttps://t.me/Bustanlikspecializedschool\n\n🎮 Discord сервер (управляется старшим учеником):\nhttps://discord.gg/RsSFaC8zX",
        'anonim_start_msg': "✍️ Вы можете написать свое обращение.\n\n📎 Вы можете отправить текст, изображение, голосовое сообщение или файл.",
        'anonim_category_prompt': "Выберите тип вашего обращения:",
        'category_suggestion': "Предложение",
        'category_complaint': "Жалоба",
        'category_question': "Вопрос",
        'new_anonim_request': "📩 Новое анонимное обращение",
        'admin_reply_button': "Ответить",
        'user_id_not_found': "❌ Идентификатор пользователя не найден. Пожалуйста, ответьте через кнопку 'Ответить'.",
        'admin_reply_prompt': "Вы можете написать ответ пользователю с ID: `{user_id}`.",
        'admin_reply_sent': "✅ Ответ отправлен.",
        'error_occurred': "❌ Произошла ошибка. Попробуйте еще раз.",
        'content_not_accepted': "⚠️ Этот тип контента не принимается.",
        'request_sent': "✅ Ваше обращение отправлено. Спасибо.",
        'language_select_prompt': "Tilni tanlang: / Choose language: / Выберите язык:",
        'language_selected': "Язык установлен на русский.",
        'admin_answer': "📬 Ответ администратора",
        'status_title': "Статус сообщения",
        'status_category': "Категория",
        'status_label': "Статус",
        'status_sent_at': "Время отправки",
        'status_answered_at': "Время ответа",
        'status_no_messages': "Вы ещё не отправляли сообщений.",
        'status_pending': "Ожидает ответа",
        'status_answered': "Отвечено",
        'status_reviewing': "Рассматривается",
    },
    'en': {
        'welcome': "Hello {mention}! \n\nWelcome to the anonymous appeal bot of Bustanlik District Specialized School.\n\n📨 Anonymous appeal: /anonim\nℹ️ About the school: /info\n🔗 Telegram channel and Discord server: /links",
        'info_text': "🏫 Our school was established in 2022, and the main goal is to provide students with quality education and wide opportunities. Our school is a modern educational institution providing high-quality education for grades 5-11. The school team is ready for friendly cooperation.\n\nIn our school:\n- Modern subject lessons (mathematics, physics, English, chemistry, biology, and others)\n- Sports and creative clubs.\n- Opportunity to participate in competitions and projects.\n\nYou will develop knowledge and friendship with us.\nJoin our Telegram channel for more news!",
        'links_text': "📢 Telegram channel:\nhttps://t.me/Bustanlikspecializedschool\n\n🎮 Discord server (run and managed by senior student):\nhttps://discord.gg/RsSFaC8zX",
        'anonim_start_msg': "✍️ You can write your appeal.\n\n📎 You can send text, image, voice message, or file.",
        'anonim_category_prompt': "Select the type of your appeal:",
        'category_suggestion': "Suggestion",
        'category_complaint': "Complaint",
        'category_question': "Question",
        'new_anonim_request': "📩 New anonymous appeal",
        'admin_reply_button': "Reply",
        'user_id_not_found': "❌ User ID not found. Please reply via the 'Reply' button.",
        'admin_reply_prompt': "You can write a reply to user ID: `{user_id}`.",
        'admin_reply_sent': "✅ Reply sent.",
        'error_occurred': "❌ An error occurred. Please try again.",
        'content_not_accepted': "⚠️ This type of content is not accepted.",
        'request_sent': "✅ Your appeal has been sent. Thank you.",
        'language_select_prompt': "Tilni tanlang: / Choose language: / Выберите язык:",
        'language_selected': "Language set to English.",
        'admin_answer': "📬 Admin reply",
        'status_title': "Message Status",
        'status_category': "Category",
        'status_label': "Status",
        'status_sent_at': "Sent at",
        'status_answered_at': "Answered at",
        'status_no_messages': "You haven't sent any messages yet.",
        'status_pending': "Pending",
        'status_answered': "Answered",
        'status_reviewing': "Under review",
    }
}

def get_text(key, lang='uz'):
    return LANGUAGES.get(lang, LANGUAGES['uz']).get(key, LANGUAGES['uz'][key])
